# ###
# POST http://localhost:9000/api/users/register
# Content-Type:application/json
# {
#     "email":"prathapkunarapu1@gmail.com",
#     "password":"prathap",
#     "firstName":"prathap",
#     "lastName":"kunarapu"
# }
###

POST http://localhost:9000/api/users/register
content-type: application/json

{
    
    "email":"prathapkunarapu1@gmail.com",
    "password":"prathap",
    "firstName":"prathap",
    "lastName":"kunarapu"
}

###
GET http://localhost:9000/:652ae3db3972924734d08f74